DROP DATABASE IF EXISTS supermercado;

CREATE DATABASE supermercado;

USE supermercado;

CREATE TABLE IF NOT EXISTS usuarios(
	
cpf VARCHAR (11) PRIMARY KEY NOT NULL,
nome VARCHAR(100) NOT NULL,
usuario VARCHAR(100) NOT NULL UNIQUE,
adm boolean not null
);

CREATE TABLE IF NOT EXISTS insumos(
	

nome VARCHAR (100) NOT NULL,
marca VARCHAR (100) NOT NULL,
fornecedora VARCHAR (100) NOT NULL,
descricao VARCHAR (500) NOT NULL,
valor DECIMAL (10,2) NOT NULL,
quantidade INT NOT NULL,
codBarras BIGINT PRIMARY KEY NOT NULL

);
